name: Validate build

on:
  pull_request:
    branches:
      - main

jobs:
  validate-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node and pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install project dependencies
        run: pnpm i

      - name: Run ESLint
        run: pnpm run lint
